version: '2'
services:
  app:
    container_name: kamelbox
    image: kamelbox:latest
    restart: always
    environment:
    - APPLICATION_URL=
    - GDRIVE_CLIENT_ID=<gdrive_client>
    - GDRIVE_CLIENT_SECRET=<gdrive_secret>
    - DROPBOX_CLIENT_ID=<dropbox_key>
    - ONLYOFFICE_URL=http://onlyoffice
    ports:
    - "8334:8334"
    volumes:
    - kamelbox:/app/data/state/

  onlyoffice:
    container_name: kamelbox_oods
    image: onlyoffice/documentserver:6.4.2
    restart: always
    security_opt:
      - seccomp:unconfined

volumes:
    kamelbox: {}